-- Backs the "Commenter un courriel" sidebar item (package=reception,
-- permission courriel.coment) -- registered in the menu/permissions but had
-- no table, view, or controller until now. Modeled on echanges_taches (the
-- existing tache-comment pattern), but with a real IDENTITY column from the
-- start -- see 2026-09-10-missing-pk-identity-fix.sql (the echanges_taches
-- entry in its table list) for why that matters: that table shipped without
-- one and its own insert path was broken as a result. Idempotent, safe to
-- re-run.

CREATE TABLE IF NOT EXISTS couriels_recu_commentaires (
    idcommentaire integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dateCommentaire" timestamp without time zone NOT NULL DEFAULT NOW(),
    commentaire text NOT NULL,
    "couriels_recu_idcouriels_recu" integer NOT NULL REFERENCES couriels_recu(idcouriels_recu),
    "idUser" integer NOT NULL REFERENCES t_users("idUser")
);

CREATE INDEX IF NOT EXISTS couriels_recu_commentaires__fk_courriel
    ON couriels_recu_commentaires ("couriels_recu_idcouriels_recu");
