-- Systemic leftover from the MySQL->Postgres migration where AUTO_INCREMENT
-- didn't carry over: a bunch of tables ended up with a primary key column
-- that has no IDENTITY/sequence/default, and a couple ended up with no
-- primary key constraint at all. Found by auditing every table in `public`.
--
-- Several of these are confirmed live production bugs, not just latent risk
-- -- the existing INSERT statements already omit the PK column, relying on
-- a default that was never there:
--   - cours (models/Cours.php)               -- course creation
--   - demande_conge (models/Conge.php)        -- leave requests
--   - depot_rapport (models/DepotSoutenance.php) -- internship report submission
--   - etudiant_tempon (models/Universite.php) -- student import
--   - ecard_access_keys / ecard_verification_log (models/SecurityUtils.php)
--   - couriels_recu (models/Structure.php)    -- reception module
--   - echanges_taches (controller/comment_tache.php) -- task comments
-- `indicateur`/`valeur_indicateur` (the "Indicateurs de Gestion" module) had
-- no primary key constraint at all, not just a missing identity -- found
-- while building that module's views/controllers (registered in the sidebar
-- but never implemented).
-- The remaining tables (conversation, courrier_academique, credit_ue,
-- dossier_scientifique) have no INSERT found anywhere in the codebase --
-- likely unused/unfinished features -- fixed as preventive maintenance so
-- whenever they are wired up they don't hit the same bug.
--
-- t_user_roles is excluded: composite PK (idUser, idRole), both columns are
-- always supplied explicitly on insert -- not applicable here.
--
-- Idempotent, safe to re-run.

DO $$
DECLARE
    fix RECORD;
    has_pk boolean;
BEGIN
    FOR fix IN
        SELECT * FROM (VALUES
            ('conversation',           'idconversation'),
            ('couriels_recu',          'idcouriels_recu'),
            ('courrier_academique',    'idcourrier'),
            ('cours',                  'idcours'),
            ('credit_ue',              'idcredit'),
            ('demande_conge',          'iddemande_conge'),
            ('depot_rapport',          'iddepot_rapport'),
            ('dossier_scientifique',   'iddossier'),
            ('ecard_access_keys',      'id'),
            ('ecard_verification_log', 'id'),
            ('etudiant_tempon',        'idetudiant'),
            ('echanges_taches',        'idechange'),
            ('indicateur',             'idIndicateur'),
            ('valeur_indicateur',      'idValeur')
        ) AS t(table_name, pk_column)
    LOOP
        -- indicateur/valeur_indicateur have no PK constraint at all yet -- add it first.
        SELECT EXISTS (
            SELECT 1 FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            WHERE c.relname = fix.table_name AND con.contype = 'p'
        ) INTO has_pk;

        IF NOT has_pk THEN
            EXECUTE format('ALTER TABLE %I ADD PRIMARY KEY (%I)', fix.table_name, fix.pk_column);
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM pg_attribute a
            JOIN pg_class c ON c.oid = a.attrelid
            WHERE c.relname = fix.table_name AND a.attname = fix.pk_column AND a.attidentity <> ''
        ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY', fix.table_name, fix.pk_column);
            -- Defensive: if production already has rows this dump doesn't reflect,
            -- make sure the new sequence starts past the current max instead of at 1.
            EXECUTE format(
                'SELECT setval(pg_get_serial_sequence(%L, %L), GREATEST(COALESCE((SELECT MAX(%I) FROM %I), 0) + 1, 1), false)',
                fix.table_name, fix.pk_column, fix.pk_column, fix.table_name
            );
        END IF;
    END LOOP;
END $$;

-- FK relationships the "Indicateurs de Gestion" tables never got either
-- (same missing-constraints situation as their missing PKs above).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'indicateur_categorie_fkey'
    ) THEN
        ALTER TABLE indicateur ADD CONSTRAINT indicateur_categorie_fkey
            FOREIGN KEY ("Idcategorie") REFERENCES categorie_indicateur("idCategorie");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'valeur_indicateur_indicateur_fkey'
    ) THEN
        ALTER TABLE valeur_indicateur ADD CONSTRAINT valeur_indicateur_indicateur_fkey
            FOREIGN KEY ("idIndicateur") REFERENCES indicateur("idIndicateur");
    END IF;
END $$;
