-- Table pour les liens d'inscription externe
CREATE TABLE `liens_inscription_externe` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reference` varchar(50) NOT NULL UNIQUE,
  `titre` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `promotion_id` int(11) NOT NULL,
  `annee_acad_id` int(11) NOT NULL,
  `token_unique` varchar(255) NOT NULL UNIQUE,
  `url_complete` varchar(500) NOT NULL,
  `date_debut` datetime NOT NULL,
  `date_fin` datetime NOT NULL,
  `max_inscriptions` int(11) DEFAULT NULL COMMENT 'Nombre maximum d\'inscriptions autorisées',
  `nb_inscriptions_actuelles` int(11) DEFAULT 0,
  `est_actif` tinyint(1) DEFAULT 1,
  `utiliser_docs_defaut` tinyint(1) DEFAULT 1 COMMENT 'Utiliser les documents par défaut configurés',
  `documents_personnalises` text DEFAULT NULL COMMENT 'JSON des documents spécifiques si pas défaut',
  `message_accueil` text DEFAULT NULL,
  `message_succes` text DEFAULT NULL,
  `couleur_theme` varchar(7) DEFAULT '#007bff',
  `logo_personnalise` varchar(255) DEFAULT NULL,
  `date_creation` datetime DEFAULT current_timestamp(),
  `date_modification` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `idUser` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_promotion` (`promotion_id`),
  KEY `idx_annee_acad` (`annee_acad_id`),
  KEY `idx_token` (`token_unique`),
  KEY `idx_actif` (`est_actif`),
  FOREIGN KEY (`promotion_id`) REFERENCES `promotion`(`idpromotion`) ON DELETE CASCADE,
  FOREIGN KEY (`annee_acad_id`) REFERENCES `annee_acad`(`idannee_acad`) ON DELETE CASCADE,
  FOREIGN KEY (`idUser`) REFERENCES `t_users`(`idUser`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table pour les documents requis spécifiques à un lien d'inscription
CREATE TABLE `lien_inscription_documents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lien_inscription_id` int(11) NOT NULL,
  `document_obligatoire_id` int(11) DEFAULT NULL COMMENT 'Référence au document standard si utilisé',
  `designation` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `est_obligatoire` tinyint(1) DEFAULT 1,
  `delai_jours` int(11) DEFAULT NULL,
  `ordre_affichage` int(11) DEFAULT 1,
  `date_creation` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_lien_inscription` (`lien_inscription_id`),
  KEY `idx_document_obligatoire` (`document_obligatoire_id`),
  FOREIGN KEY (`lien_inscription_id`) REFERENCES `liens_inscription_externe`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`document_obligatoire_id`) REFERENCES `documents_obligatoires`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table pour les inscriptions via lien externe
CREATE TABLE `inscriptions_externes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lien_inscription_id` int(11) NOT NULL,
  `reference_inscription` varchar(50) NOT NULL UNIQUE,
  `nom` varchar(100) NOT NULL,
  `postnom` varchar(100) NOT NULL,
  `prenom` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `telephone` varchar(50) NOT NULL,
  `date_naissance` date NOT NULL,
  `lieu_naissance` varchar(100) NOT NULL,
  `sexe` enum('M','F') NOT NULL,
  `nationalite` varchar(100) NOT NULL,
  `adresse_complete` text NOT NULL,
  `personne_contact` varchar(200) DEFAULT NULL,
  `telephone_contact` varchar(50) DEFAULT NULL,
  `donnees_supplementaires` text DEFAULT NULL COMMENT 'JSON pour données additionnelles',
  `statut` enum('En cours','Complète','Validée','Rejetée') DEFAULT 'En cours',
  `commentaire_admin` text DEFAULT NULL,
  `date_soumission` datetime DEFAULT current_timestamp(),
  `date_validation` datetime DEFAULT NULL,
  `id_validateur` int(11) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_lien_inscription` (`lien_inscription_id`),
  KEY `idx_statut` (`statut`),
  KEY `idx_email` (`email`),
  FOREIGN KEY (`lien_inscription_id`) REFERENCES `liens_inscription_externe`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`id_validateur`) REFERENCES `t_users`(`idUser`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Table pour les documents soumis via inscription externe
CREATE TABLE `documents_inscription_externe` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `inscription_externe_id` int(11) NOT NULL,
  `lien_document_id` int(11) NOT NULL,
  `nom_fichier_original` varchar(255) NOT NULL,
  `nom_fichier_stocke` varchar(255) NOT NULL,
  `chemin_fichier` varchar(500) NOT NULL,
  `taille_fichier` bigint(20) DEFAULT NULL,
  `type_mime` varchar(100) DEFAULT NULL,
  `statut_validation` enum('En attente','Validé','Rejeté') DEFAULT 'En attente',
  `commentaire_validation` text DEFAULT NULL,
  `date_upload` datetime DEFAULT current_timestamp(),
  `date_validation` datetime DEFAULT NULL,
  `id_validateur` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_inscription_externe` (`inscription_externe_id`),
  KEY `idx_lien_document` (`lien_document_id`),
  KEY `idx_statut_validation` (`statut_validation`),
  FOREIGN KEY (`inscription_externe_id`) REFERENCES `inscriptions_externes`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`lien_document_id`) REFERENCES `lien_inscription_documents`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`id_validateur`) REFERENCES `t_users`(`idUser`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;